### PR TITLE
Role hierarchy type inheritance

### PR DESCRIPTION
**Pull request by sniper7kills**
Added ability to used simple nested sets for role inheritance.

Please see updated read me.

### CODE REVIEW

**Comment by sniper7kills** [comment]
Updated to match your latest changes and pulls. (But please confirm)

**Comment by romanbican** [comment]
Thanks for your work, but this is not something what I want to implement in this package.

**Comment by sniper7kills** [comment]
That's a shame. Do you have any issues with me maintaining a renamed packaged fork, then?

**Comment by romanbican** [comment]
Do whatever you want.

**Pull request closed without merging**
