### PR TITLE
Renamed "can" to "may"

### PR DESCRIPTION
**Pull request by chrisburton**

### CODE REVIEW

**Comment by chrisburton** [comment]
README.md still needs to be updated here.

**Comment by niknetniko** [comment]
I don't really see any benefit in doing this?

Also, this is a major compatibility break with older versions.

**Comment by chrisburton** [comment]
@niknetniko The benefit in doing this is that in its current state it conflicts with Laravel's authorization.

**Comment by niknetniko** [comment]
You could also do this:

``` php
Authorizable {
        Authorizable::can insteadof HasRoleAndPermission;
        HasRoleAndPermission::can as may;
}
```

But renaming would probably be better :+1:

**Comment by chrisburton** [comment]
@niknetniko The solution was shown in `issues 110`. I still feel that this issue would become recurrent without renaming `can` to `may`. I'm not a git pro here but isn't this the benefit of version control? So we're able to pull in particular versions of software? This would be beneficial for 5.1 users while less than or equal to 5.0 users can pull in a different version of this package.

**Comment by arandilopez** [comment]
:+1:

**Comment by chrisburton** [comment]
Closing this due to the abandonment of this repo.

**Pull request closed without merging**
