### PR TITLE
Resolving: Error on Implementation in Laravel 5.3

### PR DESCRIPTION
**Pull request by httpoz**
Compatibility with L5.3. Change is() method to isRole(). Conflicts with Model::is()

@emiliomedina21

https://github.com/romanbican/roles/issues/185

### CODE REVIEW

**Comment by thachp** [comment]
@romanbican Can you merge this pull request? This is an urgent one for me.

**Comment by pedritoelcabra** [comment]
Works perfect

**Comment by pwilms** [comment]
yea please merge! :) +1

**Comment by nikolaynesov** [comment]
@romanbican can you accept this pull request please?

**Comment by nikolaynesov** [comment]
Hey guys,

To fix it temporary use this:
I. Add VCS Repo to your composer.json
`
"repositories": [
        { "type": "vcs", "url": "https://github.com/emiliomedina21/roles.git" }
    ]
`

II. Change version of the package in composer.json

`
"bican/roles": "dev-master",
`

Hopefully it may help.

@romanbican can you please make respective changes from https://github.com/emiliomedina21/roles.git or pull that

**Comment by nikolaynesov** [comment]
@thachp you can migrate to https://github.com/Zizaco/entrust in case it's very urgent for you. It took me about 30 mins to update my project to Entrust. Entrust and this one are very similar but Entrust seems to work well with Laravel 5.3. Will update you in case any issues will be found for Entrust too.

**Comment by httpoz** [comment]
Also created a similar package to this one resolving a couple of issues between then Laravel 5 and now 5.3.

I however removed permissions in favor of Laravel's authorization. Plus one other minor change. For those that use roles alone it should be a seamless implementation. 

http://github.com/httpoz/roles

**Comment by Ricky-rick** [comment]
We decided to update and maintain a copy of bican roles and merged this pull request. 
You can find it on packagist: https://packagist.org/packages/ultraware/roles

**Pull request closed without merging**
