### PR TITLE
List users with a given role / level

### LINKED ISSUE #98: list of users at or under a certain level
any easy way to get all users with same level or under (or greater for that matter) for a given level ... or even  by role such as all users containing a certain role or a role at equal or less in level

### PR DESCRIPTION
**Pull request by httpoz**
this commit fixes #98

### CODE REVIEW

**Comment by romanbican** [comment]
This is already included.

**Comment by httpoz** [comment]
Great, how do we use this... Assumed it wasnt there solely depending on the documentation for usage examples. Thanks btw
issue #98

**Comment by balping** [comment]
@romanbican 

If it's already included, could you please show how to do it? Because I dont want to modify vendor code

**Comment by balping** [comment]
Ok, I solved it with this line. However it's quite ugly. I'm still interested if there's a _built-in_ solution

```
\Bican\Roles\Models\Role::where('slug', 'admin')->first()->belongsToMany('App\User', 'role_user', 'role_id', 'user_id')->get()
```

**Comment by chrisburton** [comment]
@balping Have you seen issue [#98](https://github.com/romanbican/roles/issues/98#issuecomment-127615694)'s solution?

**Comment by balping** [comment]
Hi @christopherburton 

Yes, I have. I copied parts from that one. But it looks like to me like he's modifying vendor code.

**Comment by chrisburton** [comment]
@balping You have some options here. You can fork this project and modify it or create a new model that extends the roles model.

**Comment by balping** [comment]
Ok, thanks. Then I rather stick to my solution. I just don't understand why the project owner, @romanbican rejected this pull request. He said this functionality was already included but it's not. Thanks anyways

**Comment by arcanedev-maroc** [comment]
@balping check this https://github.com/romanbican/roles/blob/master/src/Bican/Roles/Traits/RoleHasRelations.php#L22-L25

**Comment by balping** [comment]
Ok, thanks. Sorry, I checked only the contracts folder, but not this one

**Pull request closed without merging**
