### PR TITLE
add prefix support

### PR DESCRIPTION
**Pull request by Kryptonit3**
add prefix support

### CODE REVIEW

**Comment by Kryptonit3** [comment]
add prefix support

**Comment by sniper7kills** [comment]
:thumbsup:

**Comment by coder77** [comment]
:thumbsup: effective!

**Comment by romanbican** [comment]
I don't think this is enough. What about table names in models?

**Comment by Kryptonit3** [comment]
Those are prefixed naturally with eloquent. You only need to prefix raw queries.

**Comment by Kryptonit3** [comment]
anywhere where you manually typed a table name or column.

**Comment by Kryptonit3** [comment]
just looked through everything and it appears that was the only place where you manually called tables and columns.

**Comment by coder77** [comment]
Good job :thumbsup:

**Comment by romanbican** [comment]
Thanks for PR.

**Pull request merged**
