### PR TITLE
Fixed a bug where the cached copy of relations would get out of sync

### PR DESCRIPTION
**Pull request by jonjonw**
It seems that an empty collection gets cached for $this->roles and the check doesn't replace it. Laravel already provides lazy eager loading so I changed the getRoles() and getPermissions() functions to use that.

Here is the unit test that catches it. I suspect that it happens when a role is attached. This pull request makes the unit test pass.

```
<?php

use App\User\Role;
use App\User\Permission;
use App\User\User;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class RoleTest extends TestCase
{
    use DatabaseMigrations;

    public function testAttachRole() {
        $adminRole = $nonAdminUser = factory(Role::class)
            ->create(['slug' => 'admin', 'level' => 1000]);

        $adminUser = factory(User::class)
            ->create(['email' => 'admin@example.com']);
        $adminUser->attachRole($adminRole);

        $this->assertTrue($adminUser->isAdmin());
    }
}
```

### CODE REVIEW

**Comment by jonjonw** [comment]
This needs more work. It works for getRoles() but getPermissions() was a bad copy and paste fix that doesn't work yet.

**Comment by jonjonw** [comment]
Looked at getPermissions() and removed the caching since the role trait can't invalidate the cache. The pull request is okay now if you want to consider merging.

**Comment by romanbican** [comment]
I actually know about this problem. When you attach role or permission, it doesn't reflect right away, because of caching. You must refresh the page. That's why your test isn't working, but in normal application it's okay.

I don't want to remove caching and especially permissions caching.

I was think that we can make caching optional, or something like that.

**Comment by jonjonw** [comment]
Sounds like a good plan. Alternatively, you could use events/listeners to notify about a change to the permissions/roles and invalidate the cache.

**Pull request closed without merging**
