### PR TITLE
Directly Str class instead of the helper

### PR DESCRIPTION
**Pull request by lucasmichot**

### CODE REVIEW

**Comment by romanbican** [comment]
Why?

**Comment by lucasmichot** [comment]
To avoid calling `str_is`which will itself calls `Str::is`

**Comment by Kryptonit3** [comment]
the functions look a bit cleaner IMHO. Just like how I like to use get() post() put() delete() in my routes file.

**Comment by lucasmichot** [comment]
Mostly we avoid calling an unnecessary wrapper for `Str::is` and this impacts performances.

**Comment by romanbican** [comment]
It's true. There could be for example hundreds of permissions. So it could have impact.

**Pull request merged**
