### PR TITLE
Deniable Permissions

### PR DESCRIPTION
**Pull request by sniper7kills**
Added ability to specifically deny a permission to a user regardless of what role they are assigned to.

Please see updated read me for use.

### CODE REVIEW

**Comment by sniper7kills** [comment]
Updated to match your latest changes and pulls. (But please confirm)

**Comment by romanbican** [comment]
Thanks for PR. This looks promising. I'll look at it closer when I'll have more time. I need to test it a little bit and I'll be thinking how to make it even simpler.

**Comment by sniper7kills** [comment]
I think this will be of use, when you go to implement this. 

```php
    /**
     * Get only Granted Permissions
     */
    public function grantedPermissions() {
        return $this->userPermissions()->wherePivot('granted', true);
    }
    /**
     * Get only Denied Permissions
     */
    public function deniedPermissions() {
        return $this->userPermissions()->wherePivot('granted', false);
    }
```

**Comment by arafatx** [comment]
@romanbican just to let you know that you have the best and powerful laravel ACL with middleware. Better than the Entrust. All the best!

**Comment by waylaidwanderer** [comment]
If anyone else needs this, I made a working version of this pull request here: https://github.com/waylaidwanderer/roles/commit/b6ce8d6b4f777e8e37a65d8d4968fd80eb969dbb

**Comment by SOSkr** [comment]
A small contribution


    /**
     * Get all permissions as collection.
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getPermissions()
    {

        if(!$this->permissions)
        {
            //$rolePermissions = $this->rolePermissions()->get();
            $userDeniedPermissions = $this->deniedPermissions()->get()->pluck('id')->toArray();
            $rolePermissions = $this->rolePermissions($userDeniedPermissions)->get();

            return $rolePermissions;

        }

        return $this->permissions;

        //return (!$this->permissions) ? $this->permissions = $this->rolePermissions()->get()->merge($this->userPermissions()->get()) : $this->permissions;

    }

**Comment by SOSkr** [comment]
SOSkr@8e7d390

**Pull request closed without merging**
